### ISSUE TITLE
Can't parse table at rimworldwiki.

### ISSUE THREAD

**Issue by Nakilon** [molybdenum-99/infoboxer#86]
I want to parse this table: https://rimworldwiki.com/wiki/Textiles
I see this example: https://github.com/molybdenum-99/infoboxer/wiki/Showcase
But it does not seem to work for me::
```none
irb> page = Infoboxer.wiki("https://rimworldwiki.com/api.php").get("Textiles")
=> #<Page(title: "Textiles", url: "https://rimworldwiki.com/wiki/Textiles"): +--+...>
irb> page.tables.size
=> 1
irb> page.tables.first.heading_row
=> nil
irb> page.tables.first.body_rows.map{ |row| row.cells.map &:to_s }
=> [[""]]
```

**Comment by zverok** [comment]
If you'll look into [page source](https://rimworldwiki.com/index.php?title=Textiles&action=edit), you'll see there is no table, and instead this wikicode:
```
{{#ask: [[Category:Textile]] [[Insulation - Cold Factor ::+]]
| ?Armor - Sharp Factor
| ?Armor - Blunt Factor
| ?Armor - Heat Factor
| ?Insulation - Cold Factor = Insulation - Cold (&deg;C)
| ?Insulation - Heat Factor = Insulation - Heat (&deg;C)
| ?Max Hit Points Factor
| ?Market Value Base = Market Value
| ?Beauty Factor
| ?Flammability Factor
| link = subject
| limit = 100
| mainlabel=Textile
}}
```
The `#ask` seems to be a custom [parser function](https://www.mediawiki.org/wiki/Manual:Parser_functions) of the rimworldwiki which renders the table on the fly. So, unfortunately, your best guess at extracting information would be HTML parsing (and, as a sidenote, that's why Infoboxer is not as useful in general as I imagined it to be)

**Comment by Nakilon** [comment]
Yeah, I couldn't even find the formatted network response so in the end I just copypasted the `<table>` body manually (
